### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by gep13** [Supermortal/Cake.FtpDeploy#4]
Could you please confirm if this is the repository for this package on NuGet.org?

https://www.nuget.org/packages/Cake.FtpDeploy/

Also, is there any relationship between this repository and this one:

https://github.com/stefandevo/Cake.FtpDeploy

Thanks

**Comment by Supermortal** [comment]
Yes, this is the repository for that package. No, it has no relationship to that that I'm aware of.

**Comment by gep13** [comment]
@Supermortal thanks for getting back to me.

I was concerned that there was a duplication of effort happening, but looking again, it looks like the other repository was just the start of an idea, and no actual code has been written.
